spec:
  session:
    applications:
      terminal:
        enabled: true
        layout: split/2
    ingresses:
    - name: installer
      port: 8080
    dashboards:
    - name: Installer
      url: $(ingress_protocol)://$(session_namespace)-installer.$(ingress_domain)/
